name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main # il tutto parte con puch nel branch master 

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_WEBAPP_NAME: rainers-first-webapp

jobs:
  build:
    runs-on: ubuntu-latest # macchina da usare per compilare
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v3 # si prendono le action da github action marketplace - https://github.com/marketplace?type=actions - questa fa solo il checkout
      
      - name: Setup .NET 5 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies 🛠
        working-directory: ./Src # ho messo il progetto sotto Srv
        run: dotnet restore
      
      - name: Build app 🚀
        working-directory: ./Src
        run: dotnet build -c Release --no-restore

      - name: Publish app 📰
        working-directory: ./Src
        run: dotnet publish -c Release -o ./out
